<?xml version="1.0"?>
<package format="3">
  <name>dubins_curves</name>
  <version>0.0.0</version>
  <description>The dubins_curves package</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  
  <depend>geographic_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>rclcpp</depend>
  
  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
    <!-- <nav_core plugin="${prefix}/nav_core_plugin.xml" />
    <project11_navigation plugin="${prefix}/project11_navigation_plugin.xml" /> -->
  </export>
</package>
