# Service request for generating a Dubins Curves path.

geometry_msgs/Pose      start_pose
geometry_msgs/Pose      target_pose
float32                 radius
float32                 sampling_interval
---
bool                    success
geometry_msgs/PoseArray path
